---
kind: pipeline
type: docker
name: test

steps:
  - name: modules
    image: node:16
    commands:
      - npm ci > /dev/null
      - git submodule update --init --recursive

  - name: eslint
    image: node:16
    commands:
      - npm run eslint

  - name: php-lint
    image: composer:2.3
    commands:
      - composer i > /dev/null 2>&1
      - composer run lint
      - composer run cs:check

  - name: test-js-build
    image: node:16
    commands:
      - NODE_ENV=production npx webpack

  - name: test-full-build
    image: node:16
    pull: always
    commands:
      - npm ci > /dev/null
      - make > /tmp/log.txt 2>&1 || (cat /tmp/log.txt && exit 1)

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
type: docker
name: release

steps:
  - name: build
    image: garykim/personal-tools-image:latest
    pull: always
    commands:
      - krankerl package --shipped
  - name: integrity-sign
    image: nextcloudci/server:latest
    environment:
      PRIVATE_KEY:
        from_secret: signing_private_key
    commands:
      - mkdir -p $HOME/.nextcloud/certificates
      - curl --output $HOME/.nextcloud/certificates/riotchat.crt -L https://raw.githubusercontent.com/nextcloud/app-certificate-requests/master/riotchat/riotchat.crt
      - echo $PRIVATE_KEY > $HOME/.nextcloud/certificates/riotchat.key
      - php /var/www/html/occ integrity:sign-app --privateKey="$HOME/.nextcloud/certificates/riotchat.key" --certificate="$HOME/.nextcloud/certificates/riotchat.crt" --path="$(pwd)/build/artifacts/riotchat"
  - name: package
    image: garykim/personal-tools-image:latest
    pull: always
    environment:
      GITHUB_USER: gary-kim
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - (cd build/artifacts && tar -czf riotchat.tar.gz riotchat)
      - echo -en "$DRONE_TAG\n\n[See changelog here](https://github.com/gary-kim/riotchat/blob/master/CHANGELOG.md)" > releasemessage.txt
      - hub release create -a build/artifacts/riotchat.tar.gz -F releasemessage.txt $DRONE_TAG
  - name: release
    image: garykim/personal-tools-image:latest
    pull: always
    environment:
      NEXTCLOUD_APPS_TOKEN:
        from_secret: nextcloud_apps_token
      PRIVATE_KEY:
        from_secret: signing_private_key
    commands:
      - krankerl login --appstore $NEXTCLOUD_APPS_TOKEN
      - mkdir -p $HOME/.nextcloud/certificates
      - curl --output $HOME/.nextcloud/certificates/riotchat.crt -L https://raw.githubusercontent.com/nextcloud/app-certificate-requests/master/riotchat/riotchat.crt
      - echo -en $PRIVATE_KEY > $HOME/.nextcloud/certificates/riotchat.key
      - krankerl publish https://github.com/gary-kim/riotchat/releases/download/$DRONE_TAG/riotchat.tar.gz

trigger:
  event:
    - tag
---
kind: signature
hmac: be201d18d394b50caa892ad8d2f4e94b780000b1ed909dd67813634ddb7b3db0

...
